name: inventory_v3
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_dash: ^1.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  go_router: ^13.2.1
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Thin.ttf
        - asset: fonts/Lexend-ExtraLight.ttf
        - asset: fonts/Lexend-Light.ttf
        - asset: fonts/Lexend-Regular.ttf
        - asset: fonts/Lexend-Medium.ttf
        - asset: fonts/Lexend-SemiBold.ttf
        - asset: fonts/Lexend-Bold.ttf
        - asset: fonts/Lexend-ExtraBold.ttf
        - asset: fonts/Lexend-Black.ttf

  assets:
    - assets/onboarding/
    - assets/login/
    - assets/receipt/
    - assets/receipt/stepper/
    - assets/receipt/icon/
